{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "Backend-GAN",
        "description": "This is a description for Backend-GAN"
    },
    "paths": {
        "/api/v1/login": {
            "post": {
                "tags": ["Login"],
                "summary": "login as user",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "userName": { "type": "string" },
                            "password": { "type": "string" }
                        },
                        "example": {
                            "userName": "TesteStore",
                            "password": "Vovo3843"
                        }
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "tags": ["Users"],
                "summary": "creating user",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "userName": { "type": "string" },
                            "password": { "type": "string" }
                        },
                        "example": {
                            "userName": "Nilo",
                            "password": "Vovo3843",
                            "fullName": "Nilo Araujo Dias",
                            "celphone": "12988108463",
                            "adress": "",
                            "profile": 3,
                            "age": "30",
                            "acountBank": [{
                                "number": 1231231,
                                "agency": 3434,
                                "instituition": "Santander",
                                "CPF": "222.444.333-098"
                            }]
                        }
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            },
            "get": {
                "tags": ["Users"],
                "summary": "geting users",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        "/api/v1/users/{user_id}": {
            "get": {
                "tags": ["Users"],
                "summary": "Geting user by id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{

                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": "60327d65a4af5739f84a1ccc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            },
            "delete": {
                "tags": ["Users"],
                "summary": "Delete user by id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": "60327d65a4af5739f84a1ccc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        "/api/v1/influencers": {
            "post": {
                "tags": ["Influencers"],
                "summary": "Createing Influenceres",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "value",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "userName": { "type": "string" },
                                "password": { "type": "string" }
                            },
                            "example": {
                                "userId":"60ff6026ebd6e13d1c0d2dab" ,
                                "cpf": 24430939389 ,
                                "descriptionProfile":"alo alo estou testando influenciador" ,
                                "measures": {
                                    "height": "1.66",
                                    "waist": "80",
                                    "bust": "34",
                                    "hip": "454",
                                    "thigh": "12"
                                },
                                "influencerAdress": {
                                    "street": "Avenida Quintanilha Ribeirop",
                                    "number": "454",
                                    "city": "SÃ£o Paulo",
                                    "postCode": "12333039",
                                    "district": "Vila Campestre",
                                    "state": "SP",
                                    "complement": ""
                                  },
                                "influencerAcountBank": {
                                    "agency": "3445",
                                    "account": "54567898",
                                    "bank": "{ type: String }",
                                    "pixKey":"13434144gfdfgdfg"
                                  }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            },
            "get": {
                "tags": ["Influencers"],
                "summary": "Geting Influencers",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        "/api/v1/influencers/myAcount": {
            "get": {
                "tags": ["Influencers"],
                "summary": "Geting my account",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }

                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/influencers/stores": {
            "get": {
                "tags": ["Influencers"],
                "summary": "Geting my Stores",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IkxJTkNBTyBEQSBNQVNTQSIsImlkIjoiNjBmZjYwMjZlYmQ2ZTEzZDFjMGQyZGFiIiwicHJvZmlsZSI6M30sImlhdCI6MTYyNzM1MjcwMiwiZXhwIjoxNjI3MzU2MzAyfQ.K1MRRfzV3yYc1G7RNA8P3Vx0EkEZrAgrK1__ol5LtBw"
                    }

                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/influencers/{userName}/page": {
            "get": {
                "tags": ["Influencers"],
                "summary": "Geting influencer by User Name",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                },
                "parameters": [{
                    "name": "userName",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327d65a4af5739f84a1ccc"
                    }
                }]
            }
        },
        "/api/v1/stores": {
            "post": {
                "tags": ["Stores"],
                "summary": "Createing Stores",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "value",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "userName": { "type": "string" },
                                "password": { "type": "string" }
                            },
                            "example": {
                                "userId": "60ff6b7c14bfb15154c970d6",
                                "cnpj":"343200001000",
                                "descriptionProfile": "Estou aqui testando para ver se a loja funciona",
                                "storeAddress": {
                                       "city": "SÃ£o JosÃ© dos Campos",
                                       "complement": "undefined",
                                       "district": "Parque Industrial",
                                       "number": "123",
                                       "postCode": "12235590",
                                       "state": "SP",
                                       "street": "Rua Tefe"
                                    },
                                "storeAccountBank": {
                                    "account": "1212313",
                                    "agency": "0000",
                                    "document": "12312312",
                                    "pix": "156156156"
                                },
                               "influencerList":[]
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            },
            "get": {
                "tags": ["Stores"],
                "summary": "Geting Stores",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        "/api/v1/stores/{store_id}": {
            "get": {
                "tags": ["Stores"],
                "summary": "Geting store by id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "store_id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": "610049af1edcae0015ff5e89"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/stores/{store_id}/products": {
            "get": {
                "tags": ["Stores"],
                "summary": "Geting all products of the store",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [
                    {
                        "name": "store_id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": "60327fa7bc253f41f0984b29"
                        }
                    },
                    {
                    "name": "page",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "1",
                        "2",
                        "3"
                    ]
                 }
                },
                {
                    "name": "limit",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "3",
                        "5",
                        "10"
                    ]
                 }
                }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/stores/addInfluencer": {
            "post": {
                "tags": ["Stores"],
                "summary": "Add influencers at Store",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "influencerListFront",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": {
                                "influencerListFront": ["6005b5f45a614523007a8a46"]
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/stores/removeInfluencer": {
            "post": {
                "tags": ["Stores"],
                "summary": "Geting store by id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "influencerListFront",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": {
                                "influencerListFront": ["6005b5f45a614523007a8a46"]
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts": {
            "post": {
                "tags": ["Carts"],
                "summary": "Create cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                        "name": "token",
                        "in": "header",
                        "required": false,
                        "schema": {
                            "type": "apiKey",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                        }
                    },
                    {
                        "name": "influencerListFront",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": {
                                "productList": [{
                                    "productQuantity": 1,
                                    "_id": "60524c7c9e46703e40ad9891",
                                    "productId": "6092a003199efa0e28691559",
                                    "productColor": "PRETO",
                                    "productName": "Jaqueta da Renner",
                                    "productPrice": 115,
                                    "productSize": "G",
                                              "productImage": "https://media.glassdoor.com/sqll/2004495/monte-carlo-j%C3%B3ias-squarelogo-1559822834643.png"
                                  }
                                ],
                                "totalTax": 60,
                                "totalValue":115,
                                "totalQuantity":1
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/mycart": {
            "get": {
                "tags": ["Carts"],
                "summary": "Take my cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/updateCart": {
            "put": {
                "tags": ["Carts"],
                "summary": "Update cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                },
                {     "name": "token",
                      "in": "body",
                      "required": false,
                     "schema": {
                        "type": "object",
                        "example": {
                            "productList": [{
                                "productQuantity": 1,
                                "_id": "60524c7c9e46703e40ad9891",
                                "productId": "6092a003199efa0e28691559",
                                "productColor": "PRETO",
                                "productName": "Jaqueta da Renner",
                                "productPrice": 115,
                                "productSize": "G",
                                "productImage": "https://media.glassdoor.com/sqll/2004495/monte-carlo-j%C3%B3ias-squarelogo-1559822834643.png"
                          }],
                          "totalTax": 90,
	                      "totalValue":305,
	                      "totalQuantity":3
                    }
                 }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/removeProduct": {
            "delete": {
                "tags": ["Carts"],
                "summary": "Take cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/cep": {
            "post": {
                "tags": ["Carts"],
                "summary": "Take cart",
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": {
                            "CEP": "12422110"
                        }
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/cepTax": {
            "post": {
                "tags": ["Carts"],
                "summary": "Take cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": {
                            "CEP": "12422110"
                        }
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/carts/taxCart": {
            "post": {
                "tags": ["Carts"],
                "summary": "Take tax at cart",
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": {
                          "productList": ["6092a003199efa0e28691559","60ac0c571eccf93c50736778","6099c184da0fc6393811dd4f"],
                          "cepDestiny": "04675010"
                    }
                 }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/myPosts": {
            "get": {
                "tags": ["Post"],
                "summary": "Take MyPost",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/createPost": {
            "post": {
                "tags": ["Post"],
                "summary": "Creating post",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                },
                {
                    "name": "value",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "userName": { "type": "string" },
                            "password": { "type": "string" }
                        },
                        "example": {
                            "userId":"6100c5916e67aa0015396506",
                            "description":"Teste Post para Tropica",
                            "productList": ["6100ac1ad2158a1168209e7f"],
                            "technicalDetails": "gosto de usar tenis 34", 
                            "imagePostList": ["base64","outraBase64"]
                        }
                    }
                }
            ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/": {
            "delete": {
                "tags": ["Post"],
                "summary": "Delete post by id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [
                    {
                        "name": "post_id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "object",
                            "example": "60327d65a4af5739f84a1ccc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"

                    }
                }
            }
        },
        
        "/api/v1/post": {
            "get": {
                "tags": ["Post"],
                "summary": "Take All Posts",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "page",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "1",
                        "2",
                        "3"
                    ]
                 }
                },
                {   "name": "limit",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "1",
                        "5",
                        "10"
                    ]
                 }
                },
                {
                    "name": "filter",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "Camisa",
                        "Camiseta",
                        "Cropped"
                    ]
                 }
                }
                
            ],
                
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/relationed": {
            "get": {
                "tags": ["Post"],
                "summary": "Take Posts Reletianed",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "page",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "1",
                        "2",
                        "3"
                    ]
                 }
                },
                {
                    "name": "filter",
                    "in": "query",
                    "required": true,
                    "type": "array",
                    "items": {
                    "type": "string",
                    "enum": [
                        "Camisa",
                        "Camiseta",
                        "Cropped"
                    ]
                 }
                }
                
            ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/{post_id}/post": {
            "get": {
                "tags": ["Post"],
                "summary": "Take Post by Post Id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "post_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "606c41631c236f1a74d2a2d7"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/post/user/{userd_id}": {
            "get": {
                "tags": ["Post"],
                "summary": "Take All Posts by User Id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "userd_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327fa7bc253f41f0984b29"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
       },
        "/api/v1/post/postInfluencer": {
            "get": {
                "tags": ["Post"],
                "summary": "Geting all Influencer post's",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/products/post/{post_id}": {
            "get": {
                "tags": ["Products"],
                "summary": "Geting products by post_id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "post_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327fa7bc253f41f0984b29"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/products/{product_id}/product": {
            "get": {
                "tags": ["Products"],
                "summary": "Geting products by product_id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "product_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327fa7bc253f41f0984b29"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }

        },
        "/api/v1/products/{store_id}/store": {
            "get": {
                "tags": ["Products"],
                "summary": "Register products by store_id",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "store_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327fa7bc253f41f0984b29"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }

        },
        "/api/v1/products": {
            "get": {
                "tags": ["Products"],
                "summary": "Take All Products",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }

        },
        "/api/v1/products/colors": {
            "get": {
                "tags": ["Products"],
                "summary": "Take colors",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/products/sizes": {
            "get": {
                "tags": ["Products"],
                "summary": "Take sizes",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/orders/getMyOrders": {
            "get": {
                "tags": ["Orders"],
                "summary": "Take orders",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/orders/getOrderDetails/{order_id}": {
            "get": {
                "tags": ["Orders"],
                "summary": "Take orders details",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlU3RvcmUiLCJpZCI6IjYwMzI3ZDY1YTRhZjU3MzlmODRhMWNjYyIsInByb2ZpbGUiOjN9LCJpYXQiOjE2MjEzMDY4MTIsImV4cCI6MTYyMTMxMDQxMn0.F0qfUPUNbYWYQ0Jx9FLVNtIlm5oRbrNjBNPdOery03U"
                    }
                },{
                    "name": "order_id",
                    "in": "path",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": "60327fa7bc253f41f0984b29"
                    }
                }
            ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/v1/payment/buy": {
            "post": {
                "tags": ["Payments"],
                "summary": "Make Payment fo your cart",
                "consumes": [],
                "produces": ["text/plain", "application/json", "text/json"],
                "parameters": [{
                    "name": "token",
                    "in": "header",
                    "required": false,
                    "schema": {
                        "type": "apiKey",
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkUmVxdWVzdCI6eyJ1c2VyTmFtZSI6IlRlc3RlSW5mbHVlbmNlciIsImlkIjoiNjAzMjhiMDBiZGM1MzA0YTZjZGUyZGYwIiwicGVyZmlsIjoyfSwiaWF0IjoxNjEzOTkzNzY5LCJleHAiOjE2MTM5OTczNjl9.KVWJ4D1HKqPoIYSFxgBaYiUUXR33QXITEWcN1hQHoOg"
                    }
                },
                {
                    "name": "paymentList",
                    "in": "body",
                    "required": false,
                    "schema": {
                        "type": "object",
                        "example": {
                                "deliveryAdress": {
                                  "street": "testeaaa",
                                  "number": 555,
                                  "city": "SÃ£o Paulo",
                                      "state":"SP",
                                        "postCode": 12422110
                                },
                                "sendMethod":{
                                    "typeMethod": "PAC",
                                    "price": 37.00,
                                    "deliveryDateEstimated":""
                                },
                                "paymentMethod":{
                                    "typeMethod": "Paypal",
                                    "Description":"",
                                    "imageMethod":"",
                                    "credCard":"master"
                                    
                                },
                                "cartId":"60431558fc37be18b0562e9b",
                                "productList": [
                                {
                                  "_id": "6092a003199efa0e28691559",
                                  "productName": "Jaqueta da Renner",
                                  "productDescription": "Tamnho M P e G",
                                  "productPrice": 115,
                                  "productQuantity": 1,
                                        "productSize": "P",
                                        "productColor": "Roxo",
                                  "productImage": "https://tse1.mm.bing.net/th?id=OIP.0N-c1zc07K0q_9iPzN0SzwHaHa&pid=Api&P=0&w=300&h=300",
                                  "__v": 0
                                },
                                {
                                  "_id": "6092b974199efa0e2869155b",
                                  "productName": "Jaqueta da Renner",
                                  "productDescription": "Tamnho M P e G",
                                  "productPrice": 115,
                                  "productQuantity": 1,
                                        "productSize": "P",
                                        "productColor": "Roxo",
                                  "productImage": "https://tse1.mm.bing.net/th?id=OIP.0N-c1zc07K0q_9iPzN0SzwHaHa&pid=Api&P=0&w=300&h=300",
                                  "__v": 0
                                }],
                              "totalPrice": 230,
                                "productQuantity": 5
                            }
                        }
                    }
            ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }

        },
        "definitions": {}
    }
}